export const THERAPY_SPEAK_EXACT_PHRASES = [
	'I hear you.',
	"That's valid.",
	"You're brave for sharing.",
	'How does that make you feel?',
	'Hold space.',
	'Set boundaries.',
	'Your truth.',
	'Healing journey.',
	'Self-care.',
	'Triggered.',
	'Safe space.',
	'Emotional labor.',
	'Sit with that.',
	'Do the work.',
	'Lean into.',
	'Unpack that.',
	'Honor your feelings.',
	"You're enough.",
	'Toxic.',
	'Gaslighting.',
	'Boundaries.',
	'Process your emotions.',
	'Growth mindset.',
	'Inner child.',
	'Trauma response.',
	'Coping mechanism.',
	'Accountability partner.',
	'Recovery is not linear.',
	'One day at a time.',
	'Let go and let God.',
	'It works if you work it.',
	'Surrender.',
	'Higher power.'
] as const;

export const THERAPY_SPEAK_PATTERNS = [
	/^I want to acknowledge/i,
	/^I appreciate you sharing/i,
	/^Thank you for being vulnerable/i,
	/^It takes courage to/i,
	/\bjourney\b/i,
	/\bboundaries\b/i,
	/\btriggers\b/i
] as const;
